version: "3.9"

services:
  api-gateway:
    image: node:18
    working_dir: /app
    volumes:
      - ./api-gateway:/app
    command: sh -c "npm install && npm start"
    ports:
      - "8000:8000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - user-service
      - post-service

  user-service:
    image: node:18
    working_dir: /app
    volumes:
      - ./user-service:/app
    command: sh -c "npm install && npm start"
    ports:
      - "8003:8003"
    env_file:
      - ./user-service/.env

  post-service:
    image: node:18
    working_dir: /app
    volumes:
      - ./post-service:/app
    command: sh -c "npm install && npm start"
    ports:
      - "8002:8002"
    env_file:
      - ./post-service/.env

networks:
  default:
    driver: bridge
